= 6. Typeclasses

== 6.5 Writing typeclass instances

=== Exercises: Eq Instances

.1.
[source, haskell]
----
data TisAnInteger =
  TisAn Integer

instance Eq (TisAnInteger) where
  (==) (TisAn a) (TisAn a') = a == a'

λ> TisAn 4 == TisAn 4
True
λ> TisAn 4 == TisAn 0
False
----

.2.
[source, haskell]
----
data TwoIntegers =
  Two Integer Integer

instance Eq (TwoIntegers) where
  Two a b == Two c d =
    a == c && b == d

λ> Two 4 5 == Two 4 5
True
λ> Two 4 5 == Two 0 0
False
----

.3.
[source, haskell]
----
data StringOrInt
  = TisAnInt Int
  | TisAString String

instance Eq (StringOrInt) where
  TisAnInt x == TisAnInt y = x == y
  TisAString x == TisAString y = x == y
  TisAnInt _ == TisAString _ = False
  TisAString _ == TisAnInt _ = False

λ> TisAnInt 100 == TisAnInt 100
True
λ> TisAnInt 100 == TisAnInt 0
False
λ> TisAnInt 0 == TisAString "Hello"
False
λ> TisAString "hello" == TisAnInt 0
False
λ> TisAString "hello" == TisAString "bye"
False
λ> TisAString "hello" == TisAString "hello"
True
----

.4.
[source, haskell]
----
data Pair a =
  Pair a a

instance Eq a => Eq (Pair a) where
  Pair x y == Pair x' y' =
    x == x' && y == y'

λ> Pair "a" "b" == Pair "a" "b"
True
λ> Pair "a" "b" == Pair "z" "y"
False
----

.5.
[source, haskell]
----
data Tuple a b =
  Tuple a b

instance (Eq a, Eq b) => Eq (Tuple a b) where
  Tuple x y == Tuple x' y' =
    x == x' && y == y'

λ> Tuple 'a' "ok" == Tuple 'a' "ok"
True
λ> Tuple 'a' "ok" == Tuple 'b' "ko"
False
----

.6.
[source, haskell]
----
data Which a
  = ThisOne a
  | ThatOne a

instance Eq a => Eq (Which a) where
  ThisOne x == ThisOne y = x == y
  ThatOne x == ThatOne y = x == y
  ThisOne _ == ThatOne _ = False
  ThatOne _ == ThisOne _ = False

λ> ThisOne (4 :: Integer) == ThisOne (4 :: Integer)
True
λ> ThisOne (4 :: Integer) == ThisOne (5 :: Integer)
False
----

.7.
[source, haskell]
----
data EitherOr a b
  = Hello a
  | Goodbye b

instance (Eq a, Eq b) => Eq (EitherOr a b) where
  Hello x == Hello y = x == y
  Goodbye x == Goodbye y = x == y
  Hello _ == Goodbye _ = False
  Goodbye _ == Hello _ = False
----

== 6.6 Num

=== Exercises: Tuple Experiment

The functions `quotRem` and `divMod` return pairs of values, each element the result of the single calculation, for example, `quotRem 4 3 == (quot 4 3, rem 4 3)`. 

....
λ> (quot 4 3, rem 4 3) == quotRem 4 3
True
....

== 6.8 Ord

=== Exercises: Will They Work?

1. Will work, returns 5. Int is an instance of Ord. 

2. Will work, returns LT. Num instance defaults to Integer (which is constrained by Ord).

3. Will not work. Cannot compare different types.

4. Will work, returns False. Num instances default to Integer.

== 6.14 Chapter Exercises

=== Multiple Choice

1. c)
2. b)
3. a)
4. c)
5. a)

=== Does it typecheck?

1. Does not typecheck. Person does not derive Show.
2. Does not typecheck. Mood does not derive Eq.
3. :-)
   a) `Blah` or `Woot`  
   b) It will not typecheck because 9 is not of type Mood.
   c) It will not typecheck because Mood does not derive Ord.
4. Yes, it will typecheck.

=== Given a datatype declaration, what can we do?

1. No, will not typecheck. `Rocks` and `Yeah` data constructors not called.
2. Yes, typechecks. 
3. Yes, typechecks.
4. No, will not typecheck. `Papu` does not derive Ord.

=== Match the types

1. No, won't substitute. `a` type variable too polymorphic for value 1. 
2. No, won't substitute. `Num a` contraint too broad for 1.0
3. Yes, will substitute. `Fractional a` specific enough for 1.0.
4. Yes, will substitute. `RealFrac a` has instance for Float and Double.
5. Yes, will substitute, though `a` is now constrained to `Ord` instances
6. Yes, will substitute, though freud now only works with Ints.
7. No, won't substitute. Function will always return Int.
8. Same as 7.
9. Yes, will substitute. Int derives Ord.
10. Yes, will substitue. The operations implemented are compatible with Ord . 
11. No, won't substitute. `mySort` only works with concrete type `Char`

=== Type-Kwon-Do Two: Electric Typealoo

.1.
[source, haskell]
chk :: Eq b => (a -> b) -> a -> b -> Bool
chk f x y =
  f x == y

.2.
[source, haskell]
arith :: Num b
      => (a -> b)
      -> Integer
      -> a
      -> b
arith f i x =
  if i < 0
  then f x + f x
  else f x * f x