= 8. Recursion

== 8.2 Factorial!

=== Intermission: Exercise
[source, haskell]
----
applyTimes 5 (+1) 5 =
  (+1) $ applyTimes (5 - 1) (+1) 5

(+1) $ (+1) $ applyTimes (4 - 1) (+1) 5

(+1) $ (+1) $ (+1) $ applyTimes (3 - 1) (+1) 5

(+1) $ (+1) $ (+1) $ (+1) $ applyTimes (2 - 1) (+1) 5

(+1) $ (+1) $ (+1) $ (+1) $ (+1) $ applyTimes (1 - 1) (+1) 5

(+1) $ (+1) $ (+1) $ (+1) $ (+1) $ 5

(+1) $ (+1) $ (+1) $ (+1) $ 6

(+1) $ (+1) $ (+1) $ 7

(+1) $ (+1) $ 8

(+1) $ 9

10
----

== 8.6 Chapter Exercises

=== Review of types

1. d)
2. b)
3. d)
4. b)

=== Reviewing currying

1. "woops mrow woohoo!"
2. "1 mrow haha"
3. "woops mrow 2 mrow haha"
4. "woops mrow blue mrow haha"
5. "pink mrow haha mrow green mrow woops mrow blue"
6. "are mrow Pugs mrow awesome"

=== Recursion

.1.
[source, haskell]
go 15 2 0
go 13 2 1
go 11 2 2
go 9  2 3
go 7  2 4
go 5  2 5
go 3  2 6
go 1  2 7
(7, 1)

.2. 
[source, haskell]
sumNats :: (Eq a, Num a) => a -> a
sumNats 0 = 0
sumNats x =
  x + sumNats (x - 1)

.3.
[source, haskell]
multx :: (Integral a) => a -> a -> a
multx 0 _ = 0
multx _ 0 = 0
multx 1 y = y
multx x 1 = x
multx x y
  | x < 0 && y < 0 = multx (abs x) (abs y)
  | x < 0 || y < 0 = negate $ multx (abs x) (abs y)
  | otherwise =
      y + multx (x - 1) y

=== Fixing dividedBy
[source, haskell]
----
data DividedResult a
  = Result (a, a)
  | DividedByZero
  deriving Show

dividedBy :: Integral a => a -> a -> DividedResult a
dividedBy _ 0 = DividedByZero
dividedBy num denom = Result $ go num denom 0
  where go n d count
          | n < 0 && d < 0 = go (abs n) (abs d) count
          | n < 0 || d < 0 =
            (\(x, y) -> (negate x, negate y)) $ go (abs n) (abs d) count
          | n < d = (count, n)
          | otherwise =
              go (n - d) d (count + 1)
----

=== McCarthy 91 function
[source, haskell]
mc91 :: (Integral a) => a -> a
mc91 x
     | x > 100 = x - 10
     | x <= 100 =
                 mc91 $ mc91 $ x + 11

=== Numbers into words
[source, haskell]
----
module WordNumber where

import Data.List

-- careful only handles 0-9
digitToWord :: Int -> String
digitToWord 0 = "zero"
digitToWord 1 = "one"
digitToWord 2 = "two"
digitToWord 3 = "three"
digitToWord 4 = "four"
digitToWord 5 = "five"
digitToWord 6 = "six"
digitToWord 7 = "seven"
digitToWord 8 = "eight"
digitToWord 9 = "nine"

-- careful only handles natural numbers
digits :: Int -> [Int]
digits n = go n []
  where
    go 0 xs = xs
    go n xs =
      go (n `div` 10) ([n `mod` 10] ++ xs)

-- careful only handles natural numbers
wordNumber :: Int -> String
wordNumber =
  concat . intersperse "-" . map digitToWord . digits


λ> wordNumber 12324546
"one-two-three-two-four-five-four-six"
----